#!/bin/bash

# Set the paths
INCLUDE_PATH="include"
LIB_PATH="lib"
GAME_EXECUTABLE="bin/game"  # Specify the full path including the filename

# List all source files
SOURCE_FILES="main.c draw.c controls.c game.c"

# Compile the game
clang $SOURCE_FILES -o $GAME_EXECUTABLE -I $INCLUDE_PATH -L $LIB_PATH -lraylib -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL

# Check if compilation was successful
if [ $? -eq 0 ]; then
    echo "Compilation successful. Running the game..."
    # Run the game
    ./$GAME_EXECUTABLE
else
    echo "Compilation failed. Please check for errors."
fi

